name: Build BPCalculator

on:
  worflow_dispatch:

jobs:
  build_unit_test:
    name: build and test
    runs-on: windows-latest
    steps
    - uses: actions/checkout@v2
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test CA1CSDUnitTest/CA1CDSUnitTest.csproj --collect "Code coverage" 