name: OWASP Dep Checker

on:
  push:
    branches: [master]  #automatic run when uploaded

jobs:
  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: OWASP-Dep-Check
        with:
          project: 'BP-Calculator'
          path: 'https://bp-calculator.azurewebsites.net'
          format: 'HTML'
          args: >
            --failOnCVSS 8

     - name: Test Results
       uses: actions/upload-artifact@master
       with:
         name: Depcheck report
         path:{{github.workspace}}/reports